### PR TITLE
[BREAKING] switch the arguments order & es2015ify - fixes #7

### LINKED ISSUE #7: Swap indent and count attributes
Wouldn't it make more sense to swap the `indent` and `count` attributes and use a space as default `indent` character?

```js
indentString('Foo Bar', 5);
//=> '     Foo Bar'
```

### PR DESCRIPTION
**Pull request by SamVerschueren**
Renamed the argument name in the documentation as well. More consistent with other modules.

Should we add a default for `count` as well? `1` for instance.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Should we add a default for count as well? 1 for instance.

👍  (That's btw the current default)

**Comment by SamVerschueren** [comment]
Fixed and squashed!

**Comment by sindresorhus** [comment]
Looks great. Thank you. This API is much better :)

**Comment by SamVerschueren** [comment]
Awesome, thanks for merging! :) :beers:

**Pull request merged**
